name: masalressami
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
    # Firebase
  firebase_core: ^2.32.0
  firebase_analytics: ^10.7.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.6.0

  # UI Components
  animated_background: ^2.0.0
  cupertino_icons: ^1.0.2

  # Video Players
  video_player: ^2.9.2
  youtube_player_flutter: ^9.0.1

  # URL Handling
  url_launcher: ^6.3.0
  chewie: ^1.8.5
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
